[versions]
gradlePlugin = "8.1.2"
androidR8 = "8.2.24"
kotlin = "1.9.10"
googleServices = "4.4.0"
multidex = "2.0.1"
playReview = "2.0.1"
playServicesAds = "22.4.0"
firebaseCrashylytics = "2.9.9"
firebasePerf = "1.4.2"
paparazzi = "1.3.1"
coreKTX = "1.12.0"
coreSplashScreen = "1.0.1"
appCompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
lifecycle = "2.6.2"

composeCompiler = "1.5.3"
composeBom = "2023.10.01"
composeMaterial3 = "1.1.2"
composeHiltNavigation = "1.0.0"
accompanist = "0.32.0"
accompanistNavigationAnimation = "0.31.3-beta"

textRecognitionDefault = "19.0.0"
textRecognition = "16.0.0"
languageID = "17.0.0"

retrofit = "2.9.0"
retrofitKotlinxSerializationJson = "1.0.0"
kotlinxSerializationJson = "1.6.0"
kotlinxCollectionsImmutable = "0.3.6"
ksp = "1.9.10-1.0.13"
okHttp = "4.12.0"
coroutines = "1.7.3"
datastore = "1.0.0"
timber = "5.0.1"
chucker = "3.5.2"
daggerHilt = "2.48.1"

firebaseBom = "29.3.0"

billing = "6.1.0"
qonversionSdk = "6.2.0"

imageCropper = "4.5.0"
coil = "2.4.0"
balloon = "1.6.1"
lottie = "6.1.0"
markdown = "0.3.6"
toasty = "1.5.2"
telephotoZoomable = "0.7.1"

jUnit = "4.13.2"
testParameterInjector = "1.14"

detekt = "1.22.0"
spotless = "6.22.0"
composeDetekt = "0.0.26"
composeLintChecks = "1.2.0"
junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt"}
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
android-r8-plugin = { module = "com.android.tools:r8", version.ref = "androidR8"}
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashylytics" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerf" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKTX" }
core-splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashScreen" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "composeMaterial3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest" }
lifecycle-runtimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanistNavigationAnimation" }

text-recognition = { module = "com.google.android.gms:play-services-mlkit-text-recognition", version.ref = "textRecognitionDefault" }
text-recognition-chinese = { module = "com.google.android.gms:play-services-mlkit-text-recognition-chinese", version.ref = "textRecognition" }
text-recognition-japanese = { module = "com.google.android.gms:play-services-mlkit-text-recognition-japanese", version.ref = "textRecognition" }
text-recognition-korean = { module = "com.google.android.gms:play-services-mlkit-text-recognition-korean", version.ref = "textRecognition" }
language-id = { module = "com.google.android.gms:play-services-mlkit-language-id", version.ref = "languageID" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationJson" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
chucker-library = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-library-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "composeHiltNavigation" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "daggerHilt" }

play-review = { module = "com.google.android.play:review", version.ref="playReview" }
play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref="playReview" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }
firebase-performance-gradle = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerf" }

billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
qonversion-sdk = { module = "io.qonversion.android.sdk:sdk", version.ref = "qonversionSdk" }

image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "imageCropper" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
balloon-compose = { module = "com.github.skydoves:balloon-compose", version.ref = "balloon" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "markdown" }
toasty = { module = "com.github.grenderg:toasty", version.ref = "toasty" }
telephoto-zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "telephotoZoomable" }

junit = { module = "junit:junit", version.ref = "jUnit" }
coil-test = { module = "io.coil-kt:coil-test", version.ref = "coil" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazzi" }
test-parameter-injector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParameterInjector" }

compose-detekt = { module = "com.twitter.compose.rules:detekt", version.ref = "composeDetekt" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "composeLintChecks" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[bundles]
lifecyle = ["lifecycle-runtime-ktx", "lifecycle-service", "lifecycle-runtimeCompose", "lifecycle-viewModelCompose"]
coroutines = ["coroutines-android", "coroutines-core", "coroutines-play-services"]
play-review = ["play-review", "play-review-ktx"]
testing-unit = ["junit", "coroutines-test", "test-parameter-injector"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashylytics" }
firebase-performance = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
